### ISSUE TITLE
Moodle SSO - Enhance proposed login screen and revise the Terraso consent screen.

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#1007]
RA has implemented a version of Terraso SSO but we want to improve upon the experience for the user.

### Improve Moodle login screen

<img width="600" alt="image" src="https://github.com/techmatters/terraso-web-client/assets/10799815/e8773919-ce48-4233-a9b6-7d6620a7d303">

https://learn-tst.landscapes.global/login/index.php

Problems with the current screen:
- it prioritizes email/password login
- it doesn't provide a description of _what_ Terraso is or explain that people can use their current Google/Apple/Microsoft identity
- it mentions guest access - what is this?

### Terraso SSO screen
<img width="578" alt="image" src="https://github.com/techmatters/terraso-web-client/assets/10799815/ae0f29c3-0c67-4c6c-a0f0-e433998227f0">

(This is seen once the user clicks on the Terraso icon)
- lacks Terraso branding and colors

## Assumptions
- RA has the capacity to / will be able to implement our designs

## References
- Builds upon: https://github.com/techmatters/terraso-product/issues/14
- [UI Copy edit (G-doc)](https://docs.google.com/document/d/1b6cbROQUDXbmZNa8y0b9ckfOjErzSRYc-UkJj2zk0vA/edit#heading=h.c6kst1tafw9j)

## Designs 
- [Mockups (Figma)](https://www.figma.com/file/V2vch484f2clPH0G4hRhRj/Moodle-SSO_V1.0?type=design&node-id=138%3A1021&mode=design&t=7cA85ZULbtSPYxG8-1)

## Process

```[tasklist]
### Tasks
- [ ] https://github.com/techmatters/terraso-web-client/issues/1041
- [ ] https://github.com/techmatters/terraso-web-client/issues/1042
```

#### RA
- [ ] As a user on the learning platform, I want to know that Terraso is the primary way to log in (over email/password) so that I don't get confused in the future when my email doesn't show up on the Terraso platform
- [ ] As a user on the learning platform, I want to know what Terraso is, that it is free, and that you can use your work identity to create an account, so I know that it is worth clicking on

#### Consent screen
- [ ] As a user on the Terraso SSO consent screen, I should see the branding of Terraso so that I understand that I am giving *Terraso* consent to share my information.

#### Design
- [ ] Copy Editing
- [ ] Implemented as designed 
- [ ] Translated to Spanish

**Comment by Hanal-code** [comment]
RELEASED TO RA team:  Moodle login screen: https://www.figma.com/file/V2vch484f2clPH0G4hRhRj/Moodle-SSO_V1.0?type=design&node-id=157%3A984&mode=design&t=RyWe8kKOekvCAgZc-1

**Comment by DerekCaelin** [comment]
@paulschreiber would you mind copy-editing the UI text? Happy to meet if it would be helpful. 

[UI Copy edit (G-doc)](https://docs.google.com/document/d/1b6cbROQUDXbmZNa8y0b9ckfOjErzSRYc-UkJj2zk0vA/edit#heading=h.c6kst1tafw9j)

**Comment by paulschreiber** [comment]
@DerekCaelin Added comments to the document.

**Comment by DerekCaelin** [comment]
@paulschreiber thanks for the review! 

One comment: this line was meant to be displayed to users who created Terraso accounts as a part of the sign-up process as a signifier that they now have a Terraso account. Unlike ordinary Terraso users, these users will not land on the Terraso home screen but go straight to Learning Landscapes.

<img width="526" alt="image" src="https://github.com/techmatters/terraso-web-client/assets/10799815/d09d005c-33d1-4a17-874d-b644ee074f26">

I'm tempted to keep it in unless we can think of another signifier.

**Comment by paulschreiber** [comment]
It'd be good to signify that a new account has been created, but that sentence didn't make sense in the position it was in (in the middle of authentication info). We can add it to the bottom paragraph which explains what the account does.

**Comment by DerekCaelin** [comment]
I've moved the sentance to be with the explanation of what the account does - @Hanal-code please take a look at the changes.

**Comment by Hanal-code** [comment]
@DerekCaelin @paulschreiber Thx for the copy edit. I updated the button label and tweak the visual a bit. 
Here are the updated mockups: 

**[NEW TO TERRASO & MOODLE]** 
<img width="600" alt="image" src="https://github.com/techmatters/terraso-web-client/assets/92342777/3d89cbcb-7615-44d8-b8ac-739b56011beb">

**[EXISTING TERRASO USER]** 
<img width="600" alt="image" src="https://github.com/techmatters/terraso-web-client/assets/92342777/a487e9e0-aec6-4594-bad5-97ac374f8a0e">

**Comment by paulschreiber** [comment]
1. There are too many different font size here; we don't need that much hierarchy. Having everything at 16/18px would be fine.
2. Remove the link to tools — we don't want people getting distracted/leaving the signup flow.

**Comment by Hanal-code** [comment]
**UPDATED MOCKUP**
- Body copy style updated: Note that paragraph's leading is 150%, so body copy should be **16/24.** 
- the link tools has been removed.

<img width="600" alt="image" src="https://github.com/techmatters/terraso-web-client/assets/92342777/a6671d02-26cf-4bff-893f-74a8bdae95a9">

**Comment by DerekCaelin** [comment]
Unlikely learning tool will ever support Terraso
