### ISSUE TITLE
Engineering task - Generate Sample JSON file

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#1029]
Create a sample JSON file of a Landscape Profile for LandScale team to review.

Derek:

> We are attracted to the idea of users simply copying the URL to their Terraso landscape: (eg: http://app.terraso.org/landscapes/mount-kenya/ ) and pasting it somewhere in LandScale. LandScale would then go and fetch a JSON file with profile information, (Terraso would detect if it was LandScale making the query and provide a response.)

Our current thinking for next steps is to generate a sample JSON file with a sample landscape profile for your team to examine and provide feedback on.

Edita:

> I like the suggested path for this work. Please send over the JSON file.

```[tasklist]
### Tasks
- [x] Generate sample schema
- [x] Generate sample for Sacred Sierra
- [ ] Revise based of Edita feedback
```

**Comment by DerekCaelin** [comment]
### Feedback from Edita

> Hey Derek,
> 
> Hope you’re well! I’m finalizing the changes to our profile and have tried to put together the requirements for the export/import of profiles. As I said, we’ll be ready to implement this during the summer. We will have both the download/export and the upload/import options. I have a few questions for you:
> 
> Countries – just to confirm, you’re using Alpha-2-codes from https://www.iso.org/obp/ui. Is that right?
> Sharing contact details – I’m weary of adding this information to the exported file. Is it OK to leave it out?
> On your taxonomy terms, what’s the difference between the Original and English terms? We only collect information in English, so I’d fill in just the English one. Does that work or best to only fill in the original one? Also, should this be a list of strings instead of just a string?
> We do not use ‘languages’, but I noticed your proposed JSON has two different fields for them – what’s the difference? (standalone ‘languages’ and taxonomy terms).
> I’ve added all the other profile information we use
>  

The JSON file would take the following format (I’ve added ‘comments’ in blue) with added fields to represent LandScale’s profiles info, and I built onto the one you previously shared with me:

{
 "id": string, #database ID of the landscape. Ideally, unique universally.
 "name": string, #landscape name

"contact_email": string (email), #email address from contact information
 "website": string (url), #website from contact information
 "description": string, #landscape description
 "region": string (ISO country code), #Country, need to convert to ISO, see https://www.iso.org/obp/ui

“municipalities”: [string], #list of municipalities inside the boundary

“recognizedEcologicalPoliticalUnit”: Boolean, #Whether or not this landscape is operating at the scale of a recognized ecological or political unit
 "boundary": geojson, #The landscape boundary file.
 "languages": [string (ISO language code)],
 "areaTypes": [string], #This is rural/urban.
 "areaScalarHa": number, #Landscape size in hectares
 "population": number, #Landscape population
 "profileImage": string (url), #First image, URL to it hosted in LandScale
 "profileImageDescription": string, # First image description
 "taxonomyTerms": [{

#This is extra information available.
  "type": "ECOSYSTEM_TYPE" | "LIVELIHOOD" | "COMMODITY" | "ORGANIZATION" | "LANGUAGE" | "LAND_COVER",

#Ecosystem type – LandScale does not have this information.

Livelihood – list (LandScale first level) economic activities.

Commodity – list all traded commodities

Organization – list owner (and co-owner if it exists) organization(s) name(s).

Language – LandScale does not have this information

Land Cover – Land Cover (LandScale second level) categories
  "valueOriginal": string (ISO language code for languages), # LandScale does not use
  "valueEn": string, #enter value here
  "valueEs": string # LandScale does not use
 }],
 "associatedGroups": [string],  #LandScale does not have this information
 "developmentStrategy": {
  "objectives": string,  #Landscape Initiative Objectives
  "problemSituation": string, #Main landscape sustainability challenges and opportunities
  "interventionStrategy": string #LandScale does not have this information
 },

“demographics”: [{ #Population breakdowns by domicile (rural/urban), ethnicity, gender and age, if available. All given in numbers OR percentage.

“type”: “DOMICILE” | “ETHNIC_INDIGENOUS_GROUPS” | “GENDER” | “AGE”,

“unit”: “number” | “percentage”,

“breakdown”: [{

“name”: string,

“number”: number,

}],

}],

“organizationsInvolved”: {

“stakeholders”: [string], #list of organizations

“partners”: [string], #list of organizations

}

}

**Comment by DerekCaelin** [comment]
Edita's comments:

> Hey Derek,
> 
> 
> Hope you’re well! I’m finalizing the changes to our profile and have tried to put together the requirements for the export/import of profiles. As I said, we’ll be ready to implement this during the summer. We will have both the download/export and the upload/import options. I have a few questions for you:
> 
> Countries – just to confirm, you’re using Alpha-2-codes from https://www.iso.org/obp/ui. Is that right?
> Sharing contact details – I’m weary of adding this information to the exported file. Is it OK to leave it out?
> On your taxonomy terms, what’s the difference between the Original and English terms? We only collect information in English, so I’d fill in just the English one. Does that work or best to only fill in the original one? Also, should this be a list of strings instead of just a string?
> We do not use ‘languages’, but I noticed your proposed JSON has two different fields for them – what’s the difference? (standalone ‘languages’ and taxonomy terms).
> I’ve added all the other profile information we use
>  
> 
> The JSON file would take the following format (I’ve added ‘comments’ in blue) with added fields to represent LandScale’s profiles info, and I built onto the one you previously shared with me:
> 
> {
>  "id": string, #database ID of the landscape. Ideally, unique universally.
>  "name": string, #landscape name
> 
> "contact_email": string (email), #email address from contact information
>  "website": string (url), #website from contact information
>  "description": string, #landscape description
>  "region": string (ISO country code), #Country, need to convert to ISO, see https://www.iso.org/obp/ui
> 
> “municipalities”: [string], #list of municipalities inside the boundary
> 
> “recognizedEcologicalPoliticalUnit”: Boolean, #Whether or not this landscape is operating at the scale of a recognized ecological or political unit
>  "boundary": geojson, #The landscape boundary file.
>  "languages": [string (ISO language code)],
>  "areaTypes": [string], #This is rural/urban.
>  "areaScalarHa": number, #Landscape size in hectares
>  "population": number, #Landscape population
>  "profileImage": string (url), #First image, URL to it hosted in LandScale
>  "profileImageDescription": string, # First image description
>  "taxonomyTerms": [{
> 
> #This is extra information available.
>   "type": "ECOSYSTEM_TYPE" | "LIVELIHOOD" | "COMMODITY" | "ORGANIZATION" | "LANGUAGE" | "LAND_COVER",
> 
> #Ecosystem type – LandScale does not have this information.
> 
> Livelihood – list (LandScale first level) economic activities.
> 
> Commodity – list all traded commodities
> 
> Organization – list owner (and co-owner if it exists) organization(s) name(s).
> 
> Language – LandScale does not have this information
> 
> Land Cover – Land Cover (LandScale second level) categories
>   "valueOriginal": string (ISO language code for languages), # LandScale does not use
>   "valueEn": string, #enter value here
>   "valueEs": string # LandScale does not use
>  }],
>  "associatedGroups": [string],  #LandScale does not have this information
>  "developmentStrategy": {
>   "objectives": string,  #Landscape Initiative Objectives
>   "problemSituation": string, #Main landscape sustainability challenges and opportunities
>   "interventionStrategy": string #LandScale does not have this information
>  },
> 
> “demographics”: [{ #Population breakdowns by domicile (rural/urban), ethnicity, gender and age, if available. All given in numbers OR percentage.
> 
> “type”: “DOMICILE” | “ETHNIC_INDIGENOUS_GROUPS” | “GENDER” | “AGE”,
> 
> “unit”: “number” | “percentage”,
> 
> “breakdown”: [{
> 
> “name”: string,
> 
> “number”: number,
> 
> }],
> 
> }],
> 
> “organizationsInvolved”: {
> 
> “stakeholders”: [string], #list of organizations
> 
> “partners”: [string], #list of organizations
> 
> }
> 
> }
>
