### ISSUE TITLE
Design task - Create map from KML, KMZ, GeoJSON, Esri, etc. file

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#1035]
RELATED:

- [Maps in Terraso: concept matrix](https://docs.google.com/document/d/1Dkh-DvQaAkAkBUlw09KxkJJVHzpDrTjLiRQRwEiisfY/edit#heading=h.ufh2ybpikzb3)
- [Data map screen flow (old sketch)](https://app.mural.co/t/techmatters9109/m/techmatters9109/1659138611799/7c2505970a6bcd848fe23417d7fe8308b657fc24?sender=ue3adfb39ae85b9ee50a94245)
- Rough Sketch: Mural

```[tasklist]
### Tasks
- [x] Sketch the workflow
- [x] Sketch the screenflow
- [x] Get feedback from the team
- [x] Create wireframes
- [x] Review the wireframe with the team
- [x] Iterate the wireframe
```

**Prototype (Figma)**
Starts from Step 1. File: 
https://www.figma.com/proto/THhEUPoklhvtHQHUKTo8XB/Terraso_Hi-fi-ALL?page-id=1049%3A2267&type=design&node-id=1901-10251&viewport=-2632%2C998%2C0.5&t=fPMJQOgMGnP5nTQt-1&scaling=min-zoom&starting-point-node-id=1901%3A10251&mode=design

**Comment by Hanal-code** [comment]
@DerekCaelin Let me confirm my interpretation of the user story: 1) the pre-req of this feature -- the map files is already in Shared files and Link module. is it correct? That means that users won't be able to upload a new map from this new feature.  2)` I want to be able to share the map with others`  means sharing the published map, right? Both the data map and the landscape boundary feature don't support the draft state. No save function either.

**Comment by DerekCaelin** [comment]
@Hanal-code yes and yes. The flow for this assumes the user has uploaded a file to a shared folder, and they want to share the published map with someone.

**Comment by Hanal-code** [comment]
@josebui  In addition to the cllck-thru prototype, here's Dev mode link: https://www.figma.com/file/THhEUPoklhvtHQHUKTo8XB/Terraso_Hi-fi-ALL?type=design&node-id=1937-8198&mode=dev   Will you let me know if both are helpful or which is more helpful?
