### ISSUE TITLE
Download landscape profile in JSON format

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#1039]
## Problem

Users need to use their landscape’s profile information to use on other websites, especially LandScale. How might they do this?

## References

- [Product Spec](https://docs.google.com/document/d/1Qcci_HOXtwi62_Gli51LaPMvqForwwUakJo0uE33ggA/edit#heading=h.b4eice3hjq0r)

### Personas
Pia is the manager of a landscape page. 

### Scenarios
Pia is collaborating with other LPs to implement LandScale. She wants to create a LandScale profile for her landscape. 

### Assumptions
- The Landscape profile might not be completed
- The landscape will have an image (in jpg format)
- The landscape will have a geoJSON polygon

### References

- https://docs.google.com/spreadsheets/d/1q0PbMgG24Rkvnby2Oc4lfh1IT-W8aUmDLDTMAGrGZbY/edit#gid=0 
- https://github.com/techmatters/terraso-web-client/issues/1029
- https://github.com/techmatters/terraso-product/issues/9
- https://github.com/techmatters/terraso-web-client/issues/573
- [Sample landscape Profile](https://app.terraso.org/landscapes/sacred-sierra/profile))

### Conversation with Edita @ LandsScale Jan 3

> The Terraso team came up with a few ways for profile data to be imported to LandScale. 

> We are attracted to the idea of users simply copying the URL to their Terraso landscape: (eg: http://app.terraso.org/landscapes/mount-kenya/) and pasting it somewhere in LandScale. LandScale would then go and fetch a JSON file with profile information, (Terraso would detect if it was LandScale making the query and provide a response.)

> Alternatively, we could allow the user to download their profile in a given format and then upload it in LandScale as a file.

## Process
```[tasklist]
### Issues
- [x] Product task - write spec
- [ ] https://github.com/techmatters/terraso-web-client/issues/1029
- [ ] https://github.com/techmatters/terraso-web-client/issues/813
- [ ] (TBD) design task - add UI to download JSON version of landscape profile
- [ ] https://github.com/techmatters/terraso-web-client/issues/1066
- [ ] (optional) Design tweaks based on learning
- [ ] Product tests against criteria
- [ ] Translation
- [ ] QA
- [ ] Usability testing
```

### Product
- [x] as a human/bot I want to be able to view any landscape profile publicly: https://github.com/techmatters/terraso-product/issues/9 
- [ ] as a LandScale server provided with a Terraso landscape profile URL, I can download the profile in JSON format

### TBD
- [ ] as a user on the landscape profile, I can download the profile data in JSON format through a button on the UI

### Design
- [ ] implementation matches design
- [ ] other issues
**QA Test Plan** 
(TBD)

```[tasklist]
### Tasks
- [ ] "opportunities" spelling issue
- [ ] Too many groups associate with landscape
```
