### ISSUE TITLE
LandPKS - Usability Testing - Preparation

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#1101]
**Key Documents** 

- LPKS usability study plan document: https://docs.google.com/document/d/1f4-lSKkhzHuaesmrQi5SWkWJpFXgmmdCiplY4s6zbT4/edit

5-7 Participants
```[tasklist]
### Tasks
- [x] Document study goals and questions - collaborate with LPKS PM & UX
- [x] Recruit particpants
- [x] Usability study plan kickoff meeting with product team
- [ ] https://github.com/techmatters/terraso-web-client/issues/1110
- [x] Research the remote test tools
- [ ] https://github.com/techmatters/terraso-web-client/issues/1135
```
