### ISSUE TITLE
LandPKS - Usability Testing 

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#1148]
## Description
Carry out usability testing for LandPKS app:

Session Schedule: https://docs.google.com/document/d/1f4-lSKkhzHuaesmrQi5SWkWJpFXgmmdCiplY4s6zbT4/edit#bookmark=kix.ns0wipohoc9n

```[tasklist]
### Tasks
- [x] Pilot: Tricia
- [x] Iterate the study plan per pilot session: protocol, companion survey, etc.
- [x] Brad Jost
- [x] Raven
- [x] Allyson
- [x] Whitney
- [x] Shale
- [x] Neil
- [x] LPKS UT 1 Retro meeting
- [ ] https://github.com/techmatters/terraso-web-client/issues/1158
- [x] Create a study findings report
```

**Comment by Hanal-code** [comment]
UT retro board: https://app.mural.co/t/techmatters9109/m/techmatters9109/1694789490370/139ce9b79069908a1cdb9d0ac0a45a37c2d119a1?sender=ue3adfb39ae85b9ee50a94245

**Comment by Hanal-code** [comment]
UT 1 issues & plans (G-sheet): https://docs.google.com/spreadsheets/d/16kUL06qa5HnKCSzJI7CbilRHRPQjkCYmv6IJmtUTqaU/edit#gid=0

UT1 findings presentation: https://docs.google.com/presentation/d/19MqefgkCqrVDWom27Fa7r0XAcNII2xrBMLNNORFG-Ns/edit#slide=id.p

**Comment by Hanal-code** [comment]
@ltseng Yes.
