### ISSUE TITLE
UX Foundational Work - March

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#1478]
Goal: document Terraso's user research practices and tools for others to utilize & expand them. 

```[tasklist]
### Tasks
- [x] Record current methods of conducting studies (working draft below)
- [x] Catalog and templatize recommended methods and tools
- [x] Share 'Gathering research data' with others: LPKS, Aselo (wk of 3/25) - 'Show-and-Tell' on 3/27/24
```

ARTIFACTS: 
- Conducting usability study: https://docs.google.com/document/d/1GSnkx9p99QpD6R86BfZhHOXJ3sCJ8DbXfvXEysHDLwY/edit
- Gathering and Sharing Research and User Data: https://docs.google.com/document/d/1WmIGl-7pJNITHLCAFWk4_PMIt6r4176A4g6mzV8JGcY/edit
