### ISSUE TITLE
Websocket Research

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#2288]
Learn more about websockets and how we might use them to address an issue in which users continued to see a "pending" layer on the Add Map Layer screen, even after the layer was ready. 

## References
[Research doc](https://docs.google.com/document/d/1majdpuVvQE3XXdMfZ0BbOflnbOWck7tGTWOhaxIrNmM/edit)

```[tasklist]
### Tasks
- [x] Research how to use websockets to be notified once changes happen
- [x] Estimate size to resolve issue, share with Derek
- [x] Share findings with the rest of the Terraso teams (written or meeting)
```
