### ISSUE TITLE
Story Maps: user-selectable basemap

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#773]
### Problem

During the usability testing, users often expressed an interest in being able to set the background map. For some, the borderless, label-less map was fine, but others wanted the ability to see street labels, points of interest, terrain

### References:

- [Spec](https://docs.google.com/document/d/1jMg5V5AsVtjmhu3iuGMCcwDtp_YjVQKYv88VvbwMaWw/edit#heading=h.iwlyirgr7bfs)

- [Mapbox Styles API documentation](https://docs.mapbox.com/api/maps/styles/)

## Design
- [Figma](https://www.figma.com/file/THhEUPoklhvtHQHUKTo8XB/Terraso_Hi-fi-ALL?type=design&node-id=2466%3A2361&mode=design&t=Cq04rFTCdfmAD5Mk-1)
- [Copy document](https://docs.google.com/document/d/15-KgOmLAR78QjJeruHOVSF0aDQGIq6htwenmBuS3nvw/edit)

```[tasklist]
### Tasks
- [ ] https://github.com/techmatters/terraso-web-client/issues/1198
- [x] Engineering reviews design
- [ ] https://github.com/techmatters/terraso-web-client/issues/1658
```

### User stories / Acceptance criteria

- [ ] Analytics: As a PM, I want to know what style users select when they create a storymap

**Select from gallery**
- [ ] As a story map creator, I want to be able to select from a gallery of background maps for my whole story map:
  - Satellite (default): mapbox://styles/terraso/clux9zsa500k401p6grzm1xb8
  - [Detailed Satellite](https://studio.mapbox.com/styles/terraso/cltsvsgyk00gj01qeavbd6rnw/edit/#13.08/6.80408/-58.16234)
   - [Terrain](https://studio.mapbox.com/styles/terraso/cltt1087x00jm01pbfwqagsw8)

**Comment by Hanal-code** [comment]
Basemap option label ideas:

- Satellite map with roads, region boundaries, NO country boundaries --> 'Detailed Satellite map / Satellite map'
- Topographic map with road,  region boundaries --> 'Terrain map/ [Detailed Terrain](https://studio.mapbox.com/styles/terraso/cltt1087x00jm01pbfwqagsw8)'
- Satellite --> 'Satellite / Satellite Imagery' add a desc: (No boundaries or labels)
Related UX study: https://docs.google.com/document/d/15Nb7d8M2_ddFcNH89d0ZSGWdHYvz3K5EFhv3b6rchis/edit#heading=h.kt2rm6nquuwe

**Comment by DerekCaelin** [comment]
3d terrain for all the options.
