### ISSUE TITLE
Create map from KML, KMZ, GeoJSON, Esri, etc. file

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#778]
Users have uploaded a KML, Geojson, esri file file. How might they create a shareable link to a map?

## References

[Product Spec](https://docs.google.com/document/d/1eNQDRUIEff4uiTacPNyVMnZ_8go8hbZyNmOI81tB9nk/edit#heading=h.7sy8melophsg)

- [geojson.io](https://geojson.io)

- [A multilayer Esri Shapefile (UEIP, rivers and boundaries)](https://drive.google.com/file/d/1f7VaxZXfWmnPWqFaPGR79dTHcCQQ_mHM/view?usp=drive_link)
- KML files: 
[Wilderness Example_kml (1).zip](https://github.com/techmatters/terraso-web-client/files/13181023/Wilderness.Example_kml.1.zip)

Prerequisite for [Story Map: Show Points, Lines, Polygons, on story map](https://github.com/techmatters/terraso-product/issues/3)

## Assumptions:

User wants to visualize a single-layer map file, see this story from Luami: [Airtable | Everyone's app platform](https://airtable.com/appIE3c0ExjlY2N7l/tbld4yHA3PAFvJk40/viwc7dde8IAvFzQy3/recC3LzIFZ9n73Dwd?blocks=hide)
Value add: users share maps resulting from KML files to non-technical users.

```[tasklist]
### Issues
- [ ] https://github.com/techmatters/terraso-web-client/issues/1035
- [x] Design review
- [ ] https://github.com/techmatters/terraso-web-client/issues/1219
- [ ] https://github.com/techmatters/terraso-web-client/issues/1038
- [ ] (optional) Design tweaks based on learning
- [x] Product tests against criteria
- [ ] Translation
- [ ] QA
- [ ] Usability testing
- [ ] https://github.com/techmatters/terraso-web-client/issues/1270
```

### Product
- [x] as a user I want to select a map file that I have uploaded to a file sharing module for visualization, so I can choose what information I want to visualize.
- [x] as a user I want to customize the appearance of map layer (change color, change opacity)
- [x] I want to be able to provide a title and description for the map so that users know what they are looking at.
- [x] I want to be able to preview how the map will look to my audience
- [x] I want to be able to share the map with others

### Design
- [ ] Implementation matches design

### QA
```[tasklist]
### Tasks
- [x] I can view a file with lines as well as points and polygons
```
