### ISSUE TITLE
Migrate from Leaflet to Mapbox for Data Maps

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#816]
```[tasklist]
### Tasks
- [x] Generate data maps with Mapbox rather than Leaflet
- [x] Use Mapbox server (tiles) instead of producing in the browser, but use brower to generate if mapbox server is unavailable
```

Referenced in [Story Map: Show Points, Lines, Polygons, on story map#3](https://github.com/techmatters/terraso-product/issues/3)

## QA

- [x] Data maps can handle [large Modis file](https://firms.modaps.eosdis.nasa.gov/data/active_fire/modis-c6.1/csv/MODIS_C6_1_Global_7d.csv)

### Wont resolve before push to production
The following issues were encountered with data maps but were unrelated to implementation.
- [ ] #1034
- [ ] #1033

**Comment by DerekCaelin** [comment]
Location of demo point is lost in step 4 once step 5 sets viewport.

### Steps to replicate 
1. Use [Modis file](https://firms.modaps.eosdis.nasa.gov/data/active_fire/modis-c6.1/csv/MODIS_C6_1_Global_7d.csv)
2. Progress to step 5
3. Zoom to a part of the map not displayed in step 4
4. return from step 4
5. see issue

### expected behavior
the preview point is visible
<img width="624" alt="image" src="https://github.com/techmatters/terraso-web-client/assets/10799815/85e84ba5-a5ca-453a-b404-d0b6205fb812">

### actual behavior
the preview point is not visible because the window has moved away from the preview point
<img width="624" alt="image" src="https://github.com/techmatters/terraso-web-client/assets/10799815/de29b2c7-f638-46c8-8df4-95636c36c2b2">

**Comment by DerekCaelin** [comment]
@josebui since both @Hanal-code and I have reviewed and we've gone through QA, this work is ready for production!

**Comment by DerekCaelin** [comment]
Still waiting on the PR!
