### ISSUE TITLE
Extract client API code into library

### ISSUE THREAD

**Issue by shrouxm** [techmatters/terraso-web-client#838]
Since the LandPKS mobile app will be sharing a backend with the Terraso web app, and the Terraso web app is going to host some LandPKS views, there is potential/impetus for code re-use.

Some questions:
- Should we create a re-usable Terraso API client library that the web and mobile client can both depend on? (This issue assumes yes).
- Where will that library live? (My assumption is separate repo).
- How will the library be packaged/distributed? (My assumption is we will not currently bother distributing to npm, and just depend on it via git URL).
- Should we try to only include the re-used code in the library, but keep e.g. story maps API client code in the web client since we know it'll only be used there? (My assumption is it's easier to keep it all in the same place).

Update 19/04/2023:
- We had a conversation recorded here: https://docs.google.com/document/d/13ZyGeOxfJ2avDx80tLZfqVmiQOv7-UOeXbxVjqvRJ14/edit#

We agreed on the following steps forward:

```[tasklist]
### Tasks
- [ ] https://github.com/techmatters/terraso-web-client/issues/878
- [ ] https://github.com/techmatters/terraso-web-client/issues/879
- [ ] https://github.com/techmatters/terraso-web-client/issues/883
- [ ] https://github.com/techmatters/terraso-web-client/issues/880
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/27
- [ ] https://github.com/techmatters/terraso-web-client/issues/881
```

**Comment by josebui** [comment]
What will the `Terraso API client library` provides? Is the intent to reuse the code defined here: https://github.com/techmatters/terraso-web-client/blob/main/src/terrasoBackend/api.js

**Comment by josebui** [comment]
Did we decided the framework that will be used for the mobile app? I am not sure if we can share a library like this for a mobile and web client, I am not sure if everything is compatible there, but it depends on the framework I guess.

**Comment by shrouxm** [comment]
all of the frameworks under consideration are based on React, but would either use the React Native rendering library or React with MUI as we do in the web app. my thought is that the library would be concerned with retrieving data from terraso's graphql backend and then making it available through a redux store and/or hooks for consumption by a react app. the web app and mobile client would then use that library to supply data to their views

if we are able to use React with MUI for the mobile client as well we could consider having everything in one `terraso-client` repo, but i'm not sure if that's a good idea and didn't want to bother thinking about it without having confirmed it's possible to use React with MUI for the mobile client

**Comment by shrouxm** [comment]
potential code for extraction would be broadly speaking the files ending in slice/service/fragment, the code under state, and any dependencies on that code. my weakest held assumption is that we should move everything, e.g. i don't have a strong opinion that storyMaps{Service,Slice,Fragments} should move, and i'm still trying to understand the codebase so def open to suggestion!

**Comment by ltseng** [comment]
Is it possible to put a size on this @shrouxm, or is it too late?

**Comment by shrouxm** [comment]
@ltseng this doesn't have a size because it's a tracking issue, the subissues all have sizes (although they haven't been updated to the new sizing system).

**Comment by ltseng** [comment]
Whoops, my bad, that makes sense!

**Comment by ltseng** [comment]
@shrouxm It looks like most of the subtasks have been closed for this issue. Is it close to being done overall?

**Comment by shrouxm** [comment]
@ltseng i actually just moved the last task to In Review so i think it is reasonable to also move this task to In Review!

**Comment by shrouxm** [comment]
all sub-issues are complete, this is resolved now
